"""create users and recipes tables

Revision ID: 81be9ce59545
Revises: 009846c73e70
Create Date: 2025-09-26 18:04:43.466611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81be9ce59545'
down_revision = '009846c73e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
